### ISSUE TITLE
msys2过期了，下载404，编译报错

### ISSUE THREAD

**Issue by shuax** [xspeed1989/vcpkg_vc-ltl#1]
原版已经修复
https://github.com/microsoft/vcpkg/pull/30546

有没有什么办法自动同步官方修改

**Comment by xspeed1989** [comment]
已同步修改，目前只能定期手动同步官方仓库的修改，
问题已修改：
https://github.com/xspeed1989/vcpkg_vc-ltl/commit/757e95ad29d4052839958bc103c057ed6fcff774

shuax ***@***.***> 于2023年4月12日周三 10:49写道：

**Comment by shuax** [comment]
感谢作者修复

**Comment by xspeed1989** [comment]
> 感谢作者修复

@shuax 小事，你的事我现在才知道，没考虑过上诉吗？
